sudo: required 
services: 
  - docker 

before_install: 
  - sudo apt-get update
  - docker build -t bellooji/docker-react -f Dockerfile.dev . 
  

script: 
  - docker run -e CI=true bellooji/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-674293488770"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY