sudo: required 
services: 
  - docker 

before_install: 
  - sudo apt-get update
  - docker build -t bellooji/docker-react -f Dockerfile.dev . 
  

script: 
  - docker run -e CI=true bellooji/docker-react npm run test